# Generated by Django 5.2 on 2025-04-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hero_image', models.ImageField(upload_to='hero_images/')),
                ('thumbnail_image', models.ImageField(upload_to='thumbnail_images/')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
