# Generated by Django 5.2 on 2025-04-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('illustration', 'Illustration'), ('webdesign', 'Web Design'), ('graphicdesign', 'Graphic Design'), ('fullstackdev', 'Full Stack Development'), ('photography', 'Photography')], max_length=60)),
                ('description', models.TextField()),
                ('icon', models.ImageField(upload_to='icons/')),
            ],
        ),
    ]
