# Generated by Django 5.2 on 2025-04-27 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artworktool'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='artworktool',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tools', to='artwork.tooltype'),
        ),
    ]
