# Generated by Django 5.2 on 2025-04-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_tooltype_alter_artworktool_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworktool',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
