# Generated by Django 5.2 on 2025-04-27 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0004_alter_artworktool_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworktool',
            name='source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
