# Generated by Django 5.2 on 2025-04-27 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0006_entry_tools_used'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artworktool',
            options={'ordering': ['name'], 'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
